# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Jingwiw <wangjingwei@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

[package]
name = "ruyipack"
version = "0.0.1"
edition = "2024"
rust-version = "1.91"
license = "MulanPSL-2.0"
description = "Rust tooling for openRuyi RPM package workflows"
publish = false

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
dialoguer = { version = "0.12.0", default-features = false }
minijinja = { version = "2.24.0", default-features = false, features = ["serde", "debug"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.10.9"
shell-words = "1.1.1"
similar = { version = "3.2.0", default-features = false, features = ["std", "text"] }
spdx = { version = "0.13.5", default-features = false }
toml = { version = "1.1.6", default-features = false, features = ["std", "serde", "parse", "display", "preserve_order"] }
tempfile = "3.27.0"
thiserror = "2.0.18"
time = { version = "0.3.53", features = ["local-offset"] }
url = "2.5.8"

[dependencies.rpm-spec-analyzer]
version = "=0.1.3"
git = "https://github.com/openRuyi-Project/rpm-spec-tool"
rev = "9464eccc1f532e28f66e55a47aeaed959172d498"
default-features = false

[dependencies.rpm-spec]
version = "=0.4.1"
git = "https://github.com/openRuyi-Project/rpm-spec"
rev = "2d5139521c8bef5cf61cb9692d75fd0b5282ffd9"
default-features = false
features = ["parser", "printer", "serde"]

[build-dependencies]
toml = { version = "1.1.6", default-features = false, features = ["std", "serde", "parse"] }

[lints.rust]
unsafe_code = "forbid"
