#!/bin/sh
# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Jingwiw <wangjingwei@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

set -eu
cd "$(dirname "$0")/.."
cargo fmt --all -- --check
cargo test --locked
cargo clippy --locked --all-targets -- -D warnings
